name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # Install NPM dependencies, cache them correctly
      - name: Install dependencies
        working-directory: ./src
        run: yarn

      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true

          working-directory: ./src

          build: yarn build
          start: yarn start

          # build: npm run build
          # start: npm start

          # quote the url to be safe against YML parsing surprises
          wait-on: "http://localhost:3000"
